set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
SET(CMAKE_CROSSCOMPILING 1)

if(NOT TOOLCHAIN_ROOT)
    set(TOOLCHAIN_ROOT /toolchain)
endif()

set(TOOLCHAIN_LLVM_BIN ${TOOLCHAIN_ROOT}/bin)

set(TOOLCHAIN_TARGET_TRIPLE armv7em-none-eabi)
set(TOOLCHAIN_TARGET_FLAGS "-target ${TARGET_TRIPLE}")
set(TOOLCHAIN_CPU_FLAGS "-mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16")
set(TOOLCHAIN_ABI_FLAGS "-mthumb -mabi=aapcs")

set(CMAKE_SYSROOT ${TOOLCHAIN_ROOT}/armv7em-none-eabi/cortex-m4f)

set(TOOLCHAIN_C_INCLUDE_DIRS ${CMAKE_SYSROOT}/include)
set(TOOLCHAIN_CXX_INCLUDE_DIRS ${TOOLCHAIN_ROOT}/include/c++/v1/)
set(TOOLCHAIN_C_LIBRARY_DIRS ${CMAKE_SYSROOT}/lib)
set(TOOLCHAIN_CXX_LIBRARY_DIRS)

# TODO: How to add CXX directories only to CXX compilation?
include_directories(SYSTEM ${TOOLCHAIN_C_INCLUDE_DIRS} ${TOOLCHAIN_CXX_INCLUDE_DIRS})
link_directories(SYSTEM ${TOOLCHAIN_C_LIBRARY_DIRS} ${TOOLCHAIN_CXX_LIBRARY_DIRS})

set(CMAKE_C_COMPILER ${TOOLCHAIN_LLVM_BIN}/clang)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_LLVM_BIN}/clang)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_LLVM_BIN}/clang++)
set(CMAKE_C_LINKER ${TOOLCHAIN_LLVM_BIN}/ld.lld)
set(CMAKE_CXX_LINKER ${TOOLCHAIN_LLVM_BIN}/ld.lld)
link_directories(
    ${CMAKE_SYSROOT}/lib
    ${TOOLCHAIN_ROOT}/lib
    ${TOOLCHAIN_ROOT}/lib/baremetal
)

set(CMAKE_C_COMPILER_TARGET ${TOOLCHAIN_TARGET_TRIPLE})
set(CMAKE_ASM_COMPILER_TARGET ${TOOLCHAIN_TARGET_TRIPLE})
set(CMAKE_CXX_COMPILER_TARGET ${TOOLCHAIN_TARGET_TRIPLE})

